from micropython import const

# SCK_PIN = 4
# DT_PIN = 5

#  for esp32 generic wroom 32    
#     RED_PIN_LED = 12  
#     GREEN_LED_PIN = 14 
#     BLUE_LED_PIN = 25

#  for esp32 c6

# RED_LED_PIN = 18  
# GREEN_LED_PIN = 19 
# BLUE_LED_PIN = 20

    
# micropython event codes

IRQ_CENTRAL_CONNECT = const(1)
IRQ_CENTRAL_DISCONNECT = const(2)
IRQ_GATTS_WRITE = const(3)
IRQ_GATTS_READ_REQUEST = const(4)
IRQ_SCAN_RESULT = const(5)
IRQ_SCAN_DONE = const(6)
IRQ_PERIPHERAL_CONNECT = const(7)
IRQ_PERIPHERAL_DISCONNECT = const(8)
IRQ_GATTC_SERVICE_RESULT = const(9)
IRQ_GATTC_SERVICE_DONE = const(10)
IRQ_GATTC_CHARACTERISTIC_RESULT = const(11)
IRQ_GATTC_CHARACTERISTIC_DONE = const(12)
IRQ_GATTC_DESCRIPTOR_RESULT = const(13)
IRQ_GATTC_DESCRIPTOR_DONE = const(14)
IRQ_GATTC_READ_RESULT = const(15)
IRQ_GATTC_READ_DONE = const(16)
IRQ_GATTC_WRITE_DONE = const(17)
IRQ_GATTC_NOTIFY = const(18)
IRQ_GATTC_INDICATE = const(19)
IRQ_GATTS_INDICATE_DONE = const(20)
IRQ_MTU_EXCHANGED = const(21)
IRQ_L2CAP_ACCEPT = const(22)
IRQ_L2CAP_CONNECT = const(23)
IRQ_L2CAP_DISCONNECT = const(24)
IRQ_L2CAP_RECV = const(25)
IRQ_L2CAP_notifyClient_READY = const(26)
IRQ_CONNECTION_UPDATE = const(27)
IRQ_ENCRYPTION_UPDATE = const(28)
IRQ_GET_SECRET = const(29)
IRQ_SET_SECRET = const(30)


# micropython available flags for characteristics and descriptors 

FLAG_BROADCAST = const(0x0001)
FLAG_READ = const(0x0002)
FLAG_WRITE_NO_RESPONSE = const(0x0004)
FLAG_WRITE = const(0x0008)
FLAG_NOTIFY = const(0x0010)
FLAG_INDICATE = const(0x0020)
FLAG_AUTHENTICATED_SIGNED_WRITE = const(0x0040)

FLAG_AUX_WRITE = const(0x0100)
FLAG_READ_ENCRYPTED = const(0x0200)
FLAG_READ_AUTHENTICATED = const(0x0400)
FLAG_READ_AUTHORIZED = const(0x0800)
FLAG_WRITE_ENCRYPTED = const(0x1000)
FLAG_WRITE_AUTHENTICATED = const(0x2000)
FLAG_WRITE_AUTHORIZED = const(0x4000)




